---

# - name: add in k8s apt repo key
#   ansible.builtin.apt_key:
#     url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
#     state: present
#     keyring: /usr/share/keyrings/cloud.google.gpg

# - name: add in k8s apt repo
#   ansible.builtin.apt_repository:
#     repo: "deb [arch=arm64 signed-by=/usr/share/keyrings/cloud.google.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
#     update_cache: yes

# - name: Update and upgrade apt packages
#   become: true
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 86400 #One day

- name: install k8s packages
  ansible.builtin.apt:
    name: "{{ item }}={{ package_versions[item] }}"
    state: present
    update_cache: yes
    force: yes
  with_items: "{{ k8s_packages }}"

# - name: Ensure directory for nodename
#   file:
#     path: /var/lib/calico
#     state: directory
#     mode: "0644"

# - name: Ensure nodename for calico
#   shell: |
#     echo -n '{{ inventory_hostname }}' | tee /var/lib/calico/nodename

# - name: pin k8s packages
#   ansible.builtin.copy:
#     dest: "/etc/apt/preferences.d/{{ item }}"
#     content: |
#       Package: {{ item }}
#       Pin: version {{ package_versions[item] }}
#       Pin-Priority: 1002
#   with_items: "{{ k8s_packages }}"

# We don't have to configure kubelet's cgroup driver
# As of 1.21 it defaults to 'systemd' if not configured
# https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/#configuring-the-kubelet-cgroup-driver