---

- name: install k8s
  include_tasks: install.yml
  tags:
    - install

- name: init k8s
  include_tasks: init.yml
  tags:
    - init

# - name: discover node status
#   include_tasks: discover.yml

# - debug: var=node
# - debug: var=cluster

# - name: create the cluster
#   include_tasks: init.yml
#   when:
#     - node == "master"
#     - cluster != "initialized"
#   tags:
#     - init

  