---

- name: naming
  block:

    - name: change hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname_short }}"

    - name: build and replace hosts files
      template:
        src: "hosts.j2"
        dest: "/etc/hosts"
        force: yes
