---
# file: playbooks/k8s.yml

- name: k8s
  hosts: "{{ hosts_group|default('k8s') }}"
  become: true
  tags: k8s

  pre_tasks:
    - name: update packages
      ansible.builtin.package:
        update_cache: yes
        upgrade: full
        autoclean: true
        autoremove: true
        cache_valid_time: 86400 #One day
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

  roles:
    - "{{ role_name|default('k8s') }}"

  tasks:

    - name: reboot
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 3600
