---

- name: cni-plugins
  block:
    - name: create cni directory
      become: true
      file:
        dest: "/opt/cni/bin"
        state: directory
    
    - name: unarchive cni-plugins
      unarchive:
        src: https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-arm-v1.3.0.tgz
        dest: /opt/cni/bin/
        remote_src: yes

    # NOTE: Added net.ipv4.conf.all.rp_filter for Calico CNI
    - name: IP Table - File Update
      ansible.builtin.copy:
        dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.ipv4.conf.all.rp_filter         = 1

    - name: IP Table - System Enable
      ansible.builtin.command: /sbin/sysctl --system
