---

- name: install
  block:
    - name: installing containerd.io
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - "containerd.io{% if containerd_version is defined and containerd_version %}={{containerd_version}}{%endif%}"
      tags:
        - install
        - update

- name: config
  block:
    - name: ensure containerd config directory
      ansible.builtin.file:
        path: "{{ containerd_cfg_dir }}"
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: create containerd configuration file
      ansible.builtin.shell: |
        containerd config default > "{{ containerd_cfg_dir }}/config.toml"

    - name: Enable systemd cgroups for containerd
      ansible.builtin.lineinfile:
        path: "{{ containerd_cfg_dir }}/config.toml"
        regexp: '^            SystemdCgroup = false'
        line: '            SystemdCgroup = true'

    - name: add module load file for containerd
      ansible.builtin.copy:
        dest: "/etc/modules-load.d/containerd.conf"
        content: |
          overlay
          br_netfilter

    - name: add modules to running system for containerd
      ansible.builtin.shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: enable service
      ansible.builtin.service:
        name: containerd
        enabled: true
        state: started

- name: runc
  include_tasks: runc.yml

- name: cni
  include_tasks: cni.yml
